import React from 'react';
import glitchLogo from './assets/glitch_logo-wordmark.svg';

function App() {
  return (
    <div className="App">
      <header className="App-header center">
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <div className="glitchInfo spaceAfter">
          <div className="glitchBranding">
            <a href="https://glitch.com/" rel="noopener noreferrer" target="_blank"><img src={glitchLogo} alt="The Glitch logo" /></a>
          </div>
          <div className="sourceInfo">
            <span className="remixInfo">Generated by <a href="https://github.com/facebook/create-react-app" rel="noopener noreferrer" target="_blank">Create-React-App</a>, and <a href="https://github.com/joshuatz/create-react-app-glitch" rel="noopener noreferrer" target="_blank">tweaked for Glitch</a>.</span>
          </div>
        </div>
        <div className="center spaceAfter">
          <span>Modified by <a href="https://joshuatz.com/" rel="noopener noreferrer" target="_blank">Joshua Tzucker</a></span>
        </div>
        <div className="center spaceAfter">
          <span>Repo: <a href="https://github.com/joshuatz/create-react-app-glitch" rel="noopener noreferrer" target="_blank">GitHub</a></span>
        </div>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
